//! Tier-0 extraction: parse one file with tree-sitter and produce [`FileFacts`]
//! (symbols, references, imports, string mentions). Nothing here executes project code.

use crate::model::*;
use anyhow::{anyhow, Result};
use globset::{Glob, GlobSet, GlobSetBuilder};
use plumbgraph_langs::{Family, Pack};
use std::collections::{BTreeSet, HashMap, HashSet};
use streaming_iterator::StreamingIterator;
use tree_sitter::{Node, Parser, QueryCursor};

pub const MAX_FILE_BYTES: usize = 2 * 1024 * 1024;

fn globset(patterns: &[String]) -> GlobSet {
    let mut b = GlobSetBuilder::new();
    for p in patterns {
        if let Ok(g) = Glob::new(p) {
            b.add(g);
        }
    }
    b.build().unwrap_or_else(|_| GlobSet::empty())
}

/// Is `rel_path` a test (or example/bench) file according to the pack's globs?
pub fn is_test_path(pack: &Pack, rel_path: &str) -> bool {
    globset(&pack.manifest.test_globs).is_match(rel_path)
}

fn looks_generated(rel_path: &str, text: &str) -> bool {
    let lower = rel_path.to_ascii_lowercase();
    if lower.ends_with(".min.js")
        || lower.ends_with(".d.ts")
        || lower.ends_with(".d.mts")
        || lower.ends_with(".d.cts")
        || lower.ends_with(".pb.go")
    {
        return true;
    }
    text.lines().take(10).any(|l| {
        l.contains("@generated")
            || l.contains("DO NOT EDIT")
            || l.contains("Code generated")
            || l.contains("auto-generated")
            || l.contains("autogenerated")
    })
}

fn is_ident_like(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_alphabetic() || c == '_' || c == '$' => {}
        _ => return false,
    }
    s.len() <= 64 && chars.all(|c| c.is_alphanumeric() || c == '_' || c == '$')
}

struct RawDef<'t> {
    pat: usize,
    kind: String,
    def: Node<'t>,
    name_node: Node<'t>,
}

fn text<'a>(n: Node, src: &'a [u8]) -> &'a str {
    std::str::from_utf8(&src[n.start_byte()..n.end_byte()]).unwrap_or("")
}

fn rust_attrs(def: Node, src: &[u8]) -> Vec<String> {
    let mut out = vec![];
    let mut cur = def.prev_sibling();
    while let Some(s) = cur {
        match s.kind() {
            "attribute_item" => out.push(text(s, src).trim().to_string()),
            "line_comment" | "block_comment" => {}
            _ => break,
        }
        cur = s.prev_sibling();
    }
    out
}

fn attr_inner(a: &str) -> &str {
    a.trim()
        .trim_start_matches("#[")
        .trim_end_matches(']')
        .trim()
}

fn rust_attr_is_test(inner: &str) -> bool {
    inner == "test"
        || inner.ends_with("::test")
        || inner.contains("cfg(test)")
        || inner.starts_with("test_case")
        || inner == "bench"
}

const RUST_NEUTRAL_ATTRS: &[&str] = &[
    "derive",
    "doc",
    "allow",
    "warn",
    "deny",
    "forbid",
    "cfg",
    "cfg_attr",
    "inline",
    "must_use",
    "deprecated",
    "rustfmt",
    "non_exhaustive",
    "repr",
    "expect",
    "automatically_derived",
    "track_caller",
    "cold",
    "test",
    "bench",
    "ignore",
    "should_panic",
    "feature",
    "macro_use",
];

const PY_NEUTRAL_DECORATORS: &[&str] = &[
    "property",
    "staticmethod",
    "classmethod",
    "abstractmethod",
    "override",
    "overload",
    "cached_property",
    "dataclass",
    "total_ordering",
    "wraps",
    "setter",
    "getter",
    "deleter",
    "final",
    "contextmanager",
    "lru_cache",
    "cache",
    "unique",
];

fn py_decorators(def: Node, src: &[u8]) -> Vec<String> {
    let Some(p) = def.parent() else { return vec![] };
    if p.kind() != "decorated_definition" {
        return vec![];
    }
    let mut out = vec![];
    let mut c = p.walk();
    for ch in p.children(&mut c) {
        if ch.kind() == "decorator" {
            out.push(text(ch, src).trim_start_matches('@').trim().to_string());
        }
    }
    out
}

fn py_decorator_is_neutral(d: &str) -> bool {
    let head = d.split('(').next().unwrap_or(d);
    let last = head.rsplit('.').next().unwrap_or(head);
    PY_NEUTRAL_DECORATORS.contains(&last)
}

/// Modifier keywords of a Java/C# declaration (`public`, `static`, `override`, ...).
fn cl_modifiers(def: Node, src: &[u8]) -> Vec<String> {
    let mut out = vec![];
    let mut c = def.walk();
    for ch in def.children(&mut c) {
        match ch.kind() {
            "modifiers" => out.extend(
                text(ch, src)
                    .split_whitespace()
                    .filter(|w| !w.starts_with('@') && w.chars().all(|c| c.is_alphabetic()))
                    .map(String::from),
            ),
            "modifier" => out.push(text(ch, src).trim().to_string()),
            _ => {}
        }
    }
    out
}

/// Annotation / attribute names (last path segment) on a Java/C# declaration.
fn cl_annotations(def: Node, src: &[u8]) -> Vec<String> {
    fn last(t: &str) -> String {
        let head = t.split(['(', '<']).next().unwrap_or(t).trim();
        head.rsplit('.').next().unwrap_or(head).to_string()
    }
    let mut out = vec![];
    let mut stack: Vec<Node> = vec![];
    let mut c = def.walk();
    for ch in def.children(&mut c) {
        stack.push(ch);
    }
    while let Some(n) = stack.pop() {
        match n.kind() {
            "modifiers" | "attribute_list" => {
                let mut cc = n.walk();
                for x in n.children(&mut cc) {
                    stack.push(x);
                }
            }
            "annotation" | "marker_annotation" => {
                if let Some(nm) = n.child_by_field_name("name") {
                    out.push(last(text(nm, src)));
                }
            }
            "attribute" => {
                if let Some(nm) = n.child_by_field_name("name").or_else(|| n.named_child(0)) {
                    out.push(last(text(nm, src)));
                }
            }
            _ => {}
        }
    }
    out
}

const CL_TEST_ANNOTATIONS: &[&str] = &[
    "Test",
    "ParameterizedTest",
    "RepeatedTest",
    "TestFactory",
    "BeforeEach",
    "AfterEach",
    "BeforeAll",
    "AfterAll",
    "Before",
    "After",
    "BeforeClass",
    "AfterClass",
    "Fact",
    "Theory",
    "TestMethod",
    "TestCase",
    "TestCaseSource",
    "SetUp",
    "TearDown",
    "OneTimeSetUp",
    "OneTimeTearDown",
    "ClassInitialize",
    "ClassCleanup",
    "TestInitialize",
    "TestCleanup",
];

const CL_NEUTRAL_ANNOTATIONS: &[&str] = &[
    "Override",
    "Deprecated",
    "SuppressWarnings",
    "SafeVarargs",
    "FunctionalInterface",
    "Obsolete",
    "Serializable",
    "Flags",
    "DebuggerDisplay",
    "MethodImpl",
    "NonSerialized",
    "SuppressMessage",
    "Conditional",
    "Nullable",
];

/// Unity base types whose subclasses receive engine messages by method name. Names that are
/// only used by Unity; `Editor`/`EditorWindow` are generic and need `UNITY_EDITOR_BASES` context.
const UNITY_BASES: &[&str] = &[
    "MonoBehaviour",
    "ScriptableObject",
    "NetworkBehaviour",
    "StateMachineBehaviour",
    "UIBehaviour",
];
const UNITY_EDITOR_BASES: &[&str] = &["Editor", "EditorWindow"];

/// Methods the Unity engine calls by name (reflection on the message name, not a virtual call).
/// MonoBehaviour / ScriptableObject messages, physics (3D and 2D), rendering, input, animation,
/// StateMachineBehaviour, Editor/EditorWindow (incl. IHasCustomMenu) and
/// ISerializationCallbackReceiver callbacks.
const UNITY_MESSAGES: &[&str] = &[
    "Awake",
    "Start",
    "Update",
    "LateUpdate",
    "FixedUpdate",
    "OnEnable",
    "OnDisable",
    "OnDestroy",
    "OnValidate",
    "Reset",
    "OnGUI",
    "OnApplicationFocus",
    "OnApplicationPause",
    "OnApplicationQuit",
    "OnBecameVisible",
    "OnBecameInvisible",
    "OnCollisionEnter",
    "OnCollisionStay",
    "OnCollisionExit",
    "OnCollisionEnter2D",
    "OnCollisionStay2D",
    "OnCollisionExit2D",
    "OnTriggerEnter",
    "OnTriggerStay",
    "OnTriggerExit",
    "OnTriggerEnter2D",
    "OnTriggerStay2D",
    "OnTriggerExit2D",
    "OnControllerColliderHit",
    "OnJointBreak",
    "OnJointBreak2D",
    "OnParticleCollision",
    "OnParticleTrigger",
    "OnParticleSystemStopped",
    "OnMouseDown",
    "OnMouseUp",
    "OnMouseUpAsButton",
    "OnMouseEnter",
    "OnMouseExit",
    "OnMouseOver",
    "OnMouseDrag",
    "OnPreCull",
    "OnPreRender",
    "OnPostRender",
    "OnRenderImage",
    "OnRenderObject",
    "OnWillRenderObject",
    "OnDrawGizmos",
    "OnDrawGizmosSelected",
    "OnAnimatorMove",
    "OnAnimatorIK",
    "OnAudioFilterRead",
    "OnTransformChildrenChanged",
    "OnTransformParentChanged",
    "OnBeforeTransformParentChanged",
    "OnRectTransformDimensionsChange",
    "OnCanvasGroupChanged",
    "OnStateEnter",
    "OnStateExit",
    "OnStateUpdate",
    "OnStateMove",
    "OnStateIK",
    "OnStateMachineEnter",
    "OnStateMachineExit",
    "OnInspectorGUI",
    "OnSceneGUI",
    "CreateInspectorGUI",
    "CreateGUI",
    "OnSelectionChange",
    "OnFocus",
    "OnLostFocus",
    "OnHierarchyChange",
    "OnProjectChange",
    "OnInspectorUpdate",
    "AddItemsToMenu",
    "OnBeforeSerialize",
    "OnAfterDeserialize",
];

/// Unity interfaces whose methods the engine calls on any implementing type (not only
/// components): serialization callbacks, the editor's custom menu, and UI EventSystem handlers.
const UNITY_CALLBACK_INTERFACES: &[(&str, &str)] = &[
    ("ISerializationCallbackReceiver", "OnBeforeSerialize"),
    ("ISerializationCallbackReceiver", "OnAfterDeserialize"),
    ("IHasCustomMenu", "AddItemsToMenu"),
    ("IPointerEnterHandler", "OnPointerEnter"),
    ("IPointerExitHandler", "OnPointerExit"),
    ("IPointerDownHandler", "OnPointerDown"),
    ("IPointerUpHandler", "OnPointerUp"),
    ("IPointerClickHandler", "OnPointerClick"),
    ("IPointerMoveHandler", "OnPointerMove"),
    (
        "IInitializePotentialDragHandler",
        "OnInitializePotentialDrag",
    ),
    ("IBeginDragHandler", "OnBeginDrag"),
    ("IDragHandler", "OnDrag"),
    ("IEndDragHandler", "OnEndDrag"),
    ("IDropHandler", "OnDrop"),
    ("IScrollHandler", "OnScroll"),
    ("IUpdateSelectedHandler", "OnUpdateSelected"),
    ("ISelectHandler", "OnSelect"),
    ("IDeselectHandler", "OnDeselect"),
    ("IMoveHandler", "OnMove"),
    ("ISubmitHandler", "OnSubmit"),
    ("ICancelHandler", "OnCancel"),
];

/// Unity attributes that make the engine/editor call the method (or, for `InitializeOnLoad`,
/// run the class's static constructor). Matched without a trailing `Attribute`.
const UNITY_ENTRY_ATTRIBUTES: &[&str] = &[
    "RuntimeInitializeOnLoadMethod",
    "InitializeOnLoadMethod",
    "InitializeOnLoad",
    "MenuItem",
    "ContextMenu",
    "DidReloadScripts",
    "PostProcessBuild",
    "PostProcessScene",
    "OnOpenAsset",
];

/// Unity context for a C# file: under `Assets/` or `Packages/` (a Unity project layout), or
/// code (not comments or strings) that imports or names the `UnityEngine`/`UnityEditor`
/// namespaces: a `using` directive or a qualified name such as `UnityEditor.MenuItem`.
fn unity_file(rel_path: &str, root: Node, src: &[u8]) -> bool {
    let under = |dir: &str| {
        rel_path.starts_with(&format!("{dir}/")) || rel_path.contains(&format!("/{dir}/"))
    };
    if under("Assets") || under("Packages") {
        return true;
    }
    let names_unity = |t: &str| {
        let t = t.trim().trim_start_matches("global::");
        ["UnityEngine", "UnityEditor"]
            .iter()
            .any(|ns| t == *ns || t.starts_with(&format!("{ns}.")))
    };
    let mut stack = vec![root];
    while let Some(n) = stack.pop() {
        match n.kind() {
            "using_directive" => {
                let mut c = n.walk();
                if n.named_children(&mut c)
                    .any(|ch| names_unity(text(ch, src)))
                {
                    return true;
                }
            }
            "qualified_name" | "alias_qualified_name" if names_unity(text(n, src)) => return true,
            "comment"
            | "string_literal"
            | "verbatim_string_literal"
            | "raw_string_literal"
            | "interpolated_string_expression" => {}
            _ => {
                let mut c = n.walk();
                stack.extend(n.children(&mut c));
            }
        }
    }
    false
}

fn under_assets(rel_path: &str) -> bool {
    rel_path.starts_with("Assets/") || rel_path.contains("/Assets/")
}

/// Base type names (last path segment, generics stripped) of a C# class declaration.
fn cs_base_names(class_node: Node, src: &[u8]) -> Vec<String> {
    let mut out = vec![];
    let mut c = class_node.walk();
    for ch in class_node.children(&mut c) {
        if ch.kind() != "base_list" {
            continue;
        }
        let mut cc = ch.walk();
        for b in ch.named_children(&mut cc) {
            let t = text(b, src);
            let head = t.split(['<', '(']).next().unwrap_or(t).trim();
            let last = head.rsplit(['.', ':']).next().unwrap_or(head).trim();
            if !last.is_empty() {
                out.push(last.to_string());
            }
        }
    }
    out
}

/// How a C# class relates to Unity: `Some(reason)` when its methods may be called by the engine.
fn unity_class(
    class_node: Node,
    src: &[u8],
    rel_path: &str,
    in_unity_file: bool,
) -> Option<String> {
    let bases = cs_base_names(class_node, src);
    if let Some(b) = bases.iter().find(|b| UNITY_BASES.contains(&b.as_str())) {
        return Some(format!("derives from {b}"));
    }
    if in_unity_file {
        if let Some(b) = bases
            .iter()
            .find(|b| UNITY_EDITOR_BASES.contains(&b.as_str()))
        {
            return Some(format!("derives from {b}"));
        }
    }
    // .NET naming: `IDisposable`, `IComparable<T>`. A class lists its base class first and
    // cannot reach MonoBehaviour through an interface.
    let interface_like = |b: &str| {
        let mut c = b.chars();
        c.next() == Some('I') && c.next().is_some_and(|x| x.is_ascii_uppercase())
    };
    if under_assets(rel_path) && bases.first().is_some_and(|b| !interface_like(b)) {
        // indirect subclass (`Enemy : Character : MonoBehaviour`): the chain is not resolved,
        // so a class with a base class in a Unity project's Assets/ may be a component
        return Some(format!(
            "derives from {} under Assets/ (possibly an indirect MonoBehaviour)",
            bases[0]
        ));
    }
    None
}

fn unity_attribute(anns: &[String]) -> Option<&str> {
    anns.iter()
        .map(|a| a.strip_suffix("Attribute").unwrap_or(a.as_str()))
        .find(|a| UNITY_ENTRY_ATTRIBUTES.contains(a))
}

const GO_WELL_KNOWN_METHODS: &[&str] = &[
    "String",
    "Error",
    "Len",
    "Less",
    "Swap",
    "ServeHTTP",
    "MarshalJSON",
    "UnmarshalJSON",
    "MarshalText",
    "UnmarshalText",
    "Read",
    "Write",
    "Close",
    "Unwrap",
    "Is",
    "As",
    "Format",
    "Scan",
    "Value",
    "Push",
    "Pop",
    "Seek",
    "ReadFrom",
    "WriteTo",
];

fn ancestors_have_export(def: Node) -> bool {
    let mut cur = def.parent();
    for _ in 0..4 {
        let Some(n) = cur else { return false };
        match n.kind() {
            "export_statement" => return true,
            "program" | "statement_block" | "class_body" => return false,
            _ => {}
        }
        cur = n.parent();
    }
    false
}

fn js_toplevel_declarator(def: Node) -> bool {
    // variable_declarator -> lexical_declaration|variable_declaration -> program | export_statement -> program
    let Some(decl) = def.parent() else {
        return false;
    };
    if !matches!(decl.kind(), "lexical_declaration" | "variable_declaration") {
        return false;
    }
    let Some(p) = decl.parent() else { return false };
    match p.kind() {
        "program" => true,
        "export_statement" => p.parent().map(|g| g.kind() == "program").unwrap_or(false),
        _ => false,
    }
}

/// Inside a macro invocation (`token_tree`) there is no expression structure: use neighbouring tokens.
fn token_tree_member(node: Node) -> bool {
    node.parent()
        .map(|p| p.kind() == "token_tree")
        .unwrap_or(false)
        && node
            .prev_sibling()
            .map(|s| matches!(s.kind(), "." | "::"))
            .unwrap_or(false)
}

fn token_tree_call(node: Node, src: &[u8]) -> bool {
    node.parent()
        .map(|p| p.kind() == "token_tree")
        .unwrap_or(false)
        && node
            .next_sibling()
            .map(|s| s.kind() == "token_tree" && text(s, src).starts_with('('))
            .unwrap_or(false)
}

fn is_callee(node: Node) -> bool {
    let mut cur = node;
    loop {
        let Some(p) = cur.parent() else { return false };
        let field_is = |f: &str| {
            p.child_by_field_name(f)
                .map(|c| c.id() == cur.id())
                .unwrap_or(false)
        };
        match p.kind() {
            "attribute" if field_is("attribute") => cur = p,
            "member_expression" if field_is("property") => cur = p,
            "field_expression" if field_is("field") => cur = p,
            "scoped_identifier" if field_is("name") => cur = p,
            "selector_expression" if field_is("field") => cur = p,
            "member_access_expression" if field_is("name") => cur = p,
            "generic_name" => cur = p,
            "method_invocation" => return field_is("name"),
            "invocation_expression" => return field_is("function"),
            "object_creation_expression" => return field_is("type"),
            "generic_function" if field_is("function") => cur = p,
            "call" | "call_expression" => return field_is("function"),
            "new_expression" => return field_is("constructor"),
            "macro_invocation" => return field_is("macro"),
            _ => return false,
        }
    }
}

fn is_member(node: Node) -> bool {
    let Some(p) = node.parent() else { return false };
    let field_is = |f: &str| {
        p.child_by_field_name(f)
            .map(|c| c.id() == node.id())
            .unwrap_or(false)
    };
    match p.kind() {
        "attribute" => field_is("attribute"),
        "member_expression" => field_is("property"),
        "field_expression" => field_is("field"),
        "scoped_identifier" | "scoped_type_identifier" => field_is("name"),
        "selector_expression" => field_is("field"),
        "field_access" => field_is("field"),
        "member_access_expression" => field_is("name"),
        // every Java call is a method call (`foo()` means `this.foo()`)
        "method_invocation" => field_is("name"),
        // C#: `Foo()` inside a class is a method call; `Foo.Bar()` is handled above
        "invocation_expression" => field_is("function"),
        _ => false,
    }
}

/// Extract facts from source text. `rel_path` is the project-relative path using `/`.
pub fn extract(pack: &Pack, rel_path: &str, source: &str) -> Result<FileFacts> {
    let src = source.as_bytes();
    let lang = pack.language()?;
    let mut parser = Parser::new();
    parser
        .set_language(&lang)
        .map_err(|e| anyhow!("set_language: {e}"))?;
    let tree = parser
        .parse(src, None)
        .ok_or_else(|| anyhow!("parse failed for {rel_path}"))?;
    let root = tree.root_node();
    let family = pack.family();
    let file_is_test = is_test_path(pack, rel_path);

    let mut facts = FileFacts {
        lang: pack.id().to_string(),
        is_test: file_is_test,
        is_generated: looks_generated(rel_path, source),
        has_syntax_errors: root.has_error(),
        ..Default::default()
    };
    for m in &pack.manifest.dynamic_markers {
        if source.contains(m.as_str()) {
            facts.dynamic_markers.push(m.clone());
        }
    }

    // ---- definitions -------------------------------------------------------
    let defs_q = pack.defs()?;
    let names = defs_q.capture_names();
    let mut raw: Vec<RawDef> = vec![];
    {
        let mut qc = QueryCursor::new();
        let mut it = qc.matches(defs_q, root, src);
        while let Some(m) = it.next() {
            let mut kind = None;
            let mut def = None;
            let mut name_node = None;
            for c in m.captures {
                let cn = names[c.index as usize];
                if let Some(k) = cn.strip_prefix("def.") {
                    kind = Some(k.to_string());
                    def = Some(c.node);
                } else if cn == "name" {
                    name_node = Some(c.node);
                }
            }
            if let (Some(kind), Some(def), Some(name_node)) = (kind, def, name_node) {
                raw.push(RawDef {
                    pat: m.pattern_index,
                    kind,
                    def,
                    name_node,
                });
            }
        }
    }
    // Dedup by name node: keep the lowest pattern index (more specific patterns come first
    // in the file only by convention; we prefer `function` over `variable`).
    let mut best: HashMap<usize, usize> = HashMap::new();
    for (i, r) in raw.iter().enumerate() {
        let key = r.name_node.start_byte();
        match best.get(&key) {
            Some(&j) => {
                let rank = |x: &RawDef| if x.kind == "variable" { 1 } else { 0 };
                if (rank(r), r.pat) < (rank(&raw[j]), raw[j].pat) {
                    best.insert(key, i);
                }
            }
            None => {
                best.insert(key, i);
            }
        }
    }
    let mut keep_idx: Vec<usize> = best.into_values().collect();
    keep_idx.sort_by_key(|&i| {
        (
            raw[i].def.start_byte(),
            std::cmp::Reverse(raw[i].def.end_byte()),
        )
    });
    let defs: Vec<&RawDef> = keep_idx
        .iter()
        .map(|&i| &raw[i])
        .filter(|r| {
            !(family == Family::JsLike && r.kind == "variable" && !js_toplevel_declarator(r.def))
        })
        .filter(|r| {
            !(family == Family::JsLike
                && r.kind == "function"
                && r.def.kind() == "variable_declarator"
                && !js_toplevel_declarator(r.def))
        })
        .collect();

    let lines: Vec<&str> = source.lines().collect();
    let name_starts: HashSet<usize> = defs.iter().map(|d| d.name_node.start_byte()).collect();

    // Parents via stack
    let mut parents: Vec<Option<usize>> = vec![None; defs.len()];
    {
        let mut stack: Vec<usize> = vec![];
        for (i, d) in defs.iter().enumerate() {
            while let Some(&t) = stack.last() {
                if defs[t].def.end_byte() <= d.def.start_byte() {
                    stack.pop();
                } else {
                    break;
                }
            }
            parents[i] = stack.last().copied();
            stack.push(i);
        }
    }

    let base_name = rel_path.rsplit('/').next().unwrap_or(rel_path);
    let rust_main_file = base_name == "main.rs"
        || base_name == "build.rs"
        || rel_path.contains("/bin/")
        || rel_path.starts_with("bin/")
        || rel_path.contains("examples/");

    let is_csharp = pack.manifest.id == "csharp";
    let cs_unity_file = is_csharp && unity_file(rel_path, root, src);

    let mut syms: Vec<SymbolFact> = Vec::with_capacity(defs.len());
    for (i, d) in defs.iter().enumerate() {
        let mut name = text(d.name_node, src).to_string();
        let mut kind = d.kind.clone();
        let mut impl_ty = String::new();
        if family == Family::Rust && kind == "impl" {
            impl_ty = name
                .split('<')
                .next()
                .unwrap_or("")
                .trim()
                .trim_start_matches('&')
                .trim()
                .to_string();
            // a name no identifier can match, so references never resolve to the impl block itself
            name = match d.def.child_by_field_name("trait") {
                Some(t) => format!("impl {} for {}", text(t, src).trim(), impl_ty),
                None => format!("impl {impl_ty}"),
            };
        }
        let parent = parents[i];
        let mut qname = match parent {
            Some(p) => format!(
                "{}{}{}",
                syms[p].qname,
                if family == Family::Rust { "::" } else { "." },
                name
            ),
            None => name.clone(),
        };
        if kind == "impl" {
            qname = impl_ty.clone();
        }
        // Go methods live outside their type: qualify with the receiver (`Context.JSON`)
        if d.def.kind() == "method_declaration" {
            if let Some(recv) = d.def.child_by_field_name("receiver") {
                let rt = text(recv, src)
                    .trim_matches(|c| c == '(' || c == ')')
                    .split_whitespace()
                    .last()
                    .unwrap_or("")
                    .trim_start_matches('*')
                    .split('[')
                    .next()
                    .unwrap_or("")
                    .to_string();
                if !rt.is_empty() {
                    qname = format!("{rt}.{name}");
                }
            }
        }
        let mut exported;
        let mut is_test = file_is_test || parent.map(|p| syms[p].is_test).unwrap_or(false);
        let mut entry: Option<String> = None;
        let mut entry_cond: Option<String> = None;
        let mut decorated = false;
        let mut subclass_method = false;
        let mut framework_risk: Option<String> = None;

        match family {
            Family::Python => {
                let in_class = parent.map(|p| syms[p].kind == "class").unwrap_or(false);
                if kind == "function" && in_class {
                    kind = "method".into();
                }
                exported = match parent {
                    None => !name.starts_with('_'),
                    Some(p) => {
                        syms[p].exported && in_class && !name.starts_with('_') && kind == "method"
                    }
                };
                if kind == "method"
                    && name.starts_with("__")
                    && name.ends_with("__")
                    && name.len() > 4
                {
                    entry = Some("dunder method".into());
                    entry_cond = Some("parent".into());
                }
                if name.starts_with("test")
                    && kind == "function"
                    && parent.is_none()
                    && file_is_test
                {
                    is_test = true;
                }
                let decs = py_decorators(d.def, src);
                if decs.iter().any(|x| !py_decorator_is_neutral(x)) {
                    decorated = true;
                }
            }
            Family::JsLike => {
                let in_class = parent.map(|p| syms[p].kind == "class").unwrap_or(false);
                exported = match parent {
                    None => ancestors_have_export(d.def),
                    Some(p) => {
                        syms[p].exported && in_class && !name.starts_with('_') && kind == "method"
                    }
                };
                if kind == "method" {
                    if matches!(name.as_str(), "constructor") {
                        entry = Some("constructor".into());
                        entry_cond = Some("parent".into());
                    } else if matches!(
                        name.as_str(),
                        "toString"
                            | "toJSON"
                            | "valueOf"
                            | "then"
                            | "catch"
                            | "finally"
                            | "render"
                            | "componentDidMount"
                            | "componentDidUpdate"
                            | "componentWillUnmount"
                            | "ngOnInit"
                            | "ngOnDestroy"
                    ) {
                        entry = Some("well-known protocol/lifecycle method".into());
                        entry_cond = Some("parent".into());
                    }
                }
            }
            Family::ClassLike => {
                let go = pack.manifest.grammar == "go";
                let parent_kind = parent.map(|p| syms[p].kind.clone());
                let in_type = parent_kind
                    .as_deref()
                    .map(|k| matches!(k, "class" | "struct" | "interface" | "enum"))
                    .unwrap_or(false);
                if go {
                    exported = name
                        .chars()
                        .next()
                        .map(|c| c.is_uppercase())
                        .unwrap_or(false);
                    if kind == "method" && GO_WELL_KNOWN_METHODS.contains(&name.as_str()) {
                        entry = Some("well-known interface method".into());
                    }
                    if kind == "function" && parent.is_none() && name == "init" {
                        entry = Some("init function".into());
                    }
                } else {
                    let mods = cl_modifiers(d.def, src);
                    let anns = cl_annotations(d.def, src);
                    let has = |m: &str| mods.iter().any(|x| x == m);
                    let visible = has("public") || has("protected");
                    let iface_member = parent_kind.as_deref() == Some("interface");
                    exported = match parent {
                        None => has("public"),
                        Some(p) => syms[p].exported && (visible || iface_member),
                    };
                    if anns
                        .iter()
                        .any(|a| CL_TEST_ANNOTATIONS.contains(&a.as_str()))
                    {
                        is_test = true;
                    }
                    if anns.iter().any(|a| {
                        !CL_NEUTRAL_ANNOTATIONS.contains(&a.as_str())
                            && !CL_TEST_ANNOTATIONS.contains(&a.as_str())
                    }) {
                        decorated = true;
                    }
                    if kind == "method" {
                        let parent_name = parent.map(|p| syms[p].name.clone());
                        if parent_name.as_deref() == Some(name.as_str()) {
                            entry = Some("constructor".into());
                            entry_cond = Some("parent".into());
                        } else if has("override") || anns.iter().any(|a| a == "Override") {
                            entry = Some("overrides a base-class method".into());
                        } else if in_type && has("static") && (name == "main" || name == "Main") {
                            entry = Some("program entry point".into());
                        }
                    }
                    if is_csharp {
                        if let Some(a) = unity_attribute(&anns).filter(|_| cs_unity_file) {
                            if entry.is_none() {
                                entry =
                                    Some(format!("Unity `[{a}]`: invoked by the engine/editor"));
                            }
                        }
                        if entry.is_none() && cs_unity_file && kind == "method" {
                            if let Some(p) = parent
                                .filter(|&p| matches!(syms[p].kind.as_str(), "class" | "struct"))
                            {
                                let bases = cs_base_names(defs[p].def, src);
                                if let Some((iface, _)) = UNITY_CALLBACK_INTERFACES
                                    .iter()
                                    .find(|(i, m)| *m == name && bases.iter().any(|b| b == i))
                                {
                                    entry = Some(format!(
                                        "Unity callback `{name}` of `{iface}`: called by the engine"
                                    ));
                                }
                            }
                        }
                        let unity_owner = parent
                            .filter(|&p| syms[p].kind == "class")
                            .and_then(|p| unity_class(defs[p].def, src, rel_path, cs_unity_file));
                        if let (Some(why), true) = (unity_owner, kind == "method" && !has("static"))
                        {
                            if UNITY_MESSAGES.contains(&name.as_str()) {
                                if entry.is_none() {
                                    entry = Some(format!(
                                        "Unity message `{name}` (class {why}): called by the engine by name"
                                    ));
                                }
                            } else if entry.is_none() && has("public") {
                                framework_risk = Some(format!(
                                    "public method of a Unity class ({why}): may be bound to a UnityEvent (e.g. Button.onClick), an Animation Event or SendMessage in a scene, prefab or animation clip, which are not indexed"
                                ));
                            }
                        }
                    }
                }
            }
            Family::Rust => {
                let attrs = rust_attrs(d.def, src);
                let inners: Vec<&str> = attrs.iter().map(|a| attr_inner(a)).collect();
                if inners.iter().any(|a| rust_attr_is_test(a)) {
                    is_test = true;
                }
                for a in &inners {
                    let head = a.split(['(', ' ', '=']).next().unwrap_or(a);
                    if matches!(
                        head,
                        "no_mangle"
                            | "export_name"
                            | "proc_macro"
                            | "proc_macro_derive"
                            | "proc_macro_attribute"
                            | "used"
                            | "unsafe"
                    ) || a.contains("no_mangle")
                    {
                        entry = Some(format!("#[{a}]"));
                    }
                    if !RUST_NEUTRAL_ATTRS.contains(&head) && !rust_attr_is_test(a) {
                        decorated = true;
                    }
                }
                // visibility
                let mut c = d.def.walk();
                let vis = d
                    .def
                    .children(&mut c)
                    .find(|ch| ch.kind() == "visibility_modifier")
                    .map(|v| text(v, src).to_string());
                exported = vis.as_deref() == Some("pub");
                if kind == "impl" {
                    exported = false;
                    entry = Some("impl block".into());
                    entry_cond = Some(format!("type:{impl_ty}"));
                }
                // methods inside impl/trait blocks
                if kind == "function" {
                    if let Some(decl) = d.def.parent() {
                        if decl.kind() == "declaration_list" {
                            if let Some(owner) = decl.parent() {
                                match owner.kind() {
                                    "impl_item" => {
                                        kind = "method".into();
                                        let ty = owner
                                            .child_by_field_name("type")
                                            .map(|t| {
                                                text(t, src)
                                                    .split('<')
                                                    .next()
                                                    .unwrap_or("")
                                                    .trim()
                                                    .to_string()
                                            })
                                            .unwrap_or_default();
                                        qname = format!("{ty}::{name}");
                                        if owner.child_by_field_name("trait").is_some() {
                                            entry = Some("trait impl method".into());
                                            entry_cond = Some(format!("type:{ty}"));
                                            exported = false;
                                        }
                                    }
                                    "trait_item" => {
                                        kind = "method".into();
                                        entry = Some("trait default method".into());
                                        entry_cond = Some("parent".into());
                                    }
                                    _ => {}
                                }
                            }
                        }
                    }
                }
                if kind == "function" && name == "main" && parent.is_none() && rust_main_file {
                    entry = Some("binary entry point".into());
                }
            }
        }
        if kind == "method" && family != Family::Rust {
            if let Some(p) = parent {
                let class_node = defs[p].def;
                subclass_method = match family {
                    Family::Python => class_node
                        .child_by_field_name("superclasses")
                        .map(|a| {
                            let mut c = a.walk();
                            let named: Vec<String> = a
                                .named_children(&mut c)
                                .map(|n| text(n, src).to_string())
                                .collect();
                            !(named.is_empty() || named.len() == 1 && named[0] == "object")
                        })
                        .unwrap_or(false),
                    Family::ClassLike => {
                        let mut c = class_node.walk();
                        let has = class_node.children(&mut c).any(|ch| {
                            matches!(
                                ch.kind(),
                                "superclass"
                                    | "super_interfaces"
                                    | "extends_interfaces"
                                    | "base_list"
                            )
                        });
                        has
                    }
                    _ => {
                        let mut c = class_node.walk();
                        let has = class_node
                            .children(&mut c)
                            .any(|ch| ch.kind() == "class_heritage");
                        has
                    }
                };
            }
        }
        if entry.is_none() && kind == "method" && pack.manifest.id == "java" {
            if let Some(a) = java_framework_annotation(d.def, src) {
                entry = Some(format!(
                    "annotated `@{a}` (framework-managed: invoked reflectively)"
                ));
            }
        }
        if entry.is_none() && kind == "method" {
            let id = pack.manifest.id.as_str();
            if (id == "java" && name == "main") || (id == "csharp" && name == "Main") {
                entry = Some("static main entry point".into());
            } else if id == "java"
                && matches!(
                    name.as_str(),
                    "writeReplace"
                        | "readResolve"
                        | "readObject"
                        | "writeObject"
                        | "readObjectNoData"
                )
            {
                entry = Some("Java serialization hook (invoked reflectively)".into());
            }
        }
        if entry.is_none()
            && parent.is_none()
            && kind == "function"
            && pack.manifest.entry_names.contains(&name)
            && family != Family::Rust
        {
            entry = Some("conventional entry name".into());
        }
        // inline keep annotation on the definition line or the line above
        let sl = d.def.start_position().row; // 0-based
        let mut keep = None;
        for l in [sl.checked_sub(1), Some(sl)].into_iter().flatten() {
            if let Some(line) = lines.get(l) {
                if let Some(pos) = line.find("plumb:keep") {
                    let rest = &line[pos + "plumb:keep".len()..];
                    let reason = rest
                        .strip_prefix('(')
                        .and_then(|r| r.split(')').next())
                        .unwrap_or("kept")
                        .to_string();
                    keep = Some(reason);
                }
            }
        }
        syms.push(SymbolFact {
            name,
            qname,
            kind,
            start_line: d.def.start_position().row as u32 + 1,
            end_line: d.def.end_position().row as u32 + 1,
            start_byte: d.def.start_byte(),
            end_byte: d.def.end_byte(),
            exported,
            is_test,
            entry,
            entry_cond,
            decorated,
            subclass_method,
            framework_risk,
            keep,
            parent,
        });
    }

    // ---- imports -----------------------------------------------------------
    let imports_q = pack.imports()?;
    let inames = imports_q.capture_names();
    let mut import_node_ids: HashSet<usize> = HashSet::new();
    let mut by_stmt: Vec<(usize, ImportFact)> = vec![];
    let mut name_only: HashMap<usize, Vec<String>> = HashMap::new();
    // `x as y` bindings: a use of `y` in this file is a use of `x`.
    let mut aliases: HashMap<String, String> = HashMap::new();
    let mut alias_stmts: HashSet<usize> = HashSet::new();
    let mut reexports: Vec<(usize, RefFact)> = vec![];
    {
        let mut qc = QueryCursor::new();
        let mut it = qc.matches(imports_q, root, src);
        while let Some(m) = it.next() {
            let mut stmt: Option<Node> = None;
            let mut module: Option<String> = None;
            let mut imp_names: Vec<String> = vec![];
            for c in m.captures {
                match inames[c.index as usize] {
                    "import" => stmt = Some(c.node),
                    "module" => {
                        module = Some(
                            text(c.node, src)
                                .split_whitespace()
                                .collect::<Vec<_>>()
                                .join(" "),
                        )
                    }
                    "name" => imp_names.push(text(c.node, src).to_string()),
                    _ => {}
                }
            }
            if let Some(stmt) = stmt {
                if alias_stmts.insert(stmt.id()) {
                    let n_before = aliases.len();
                    collect_import_aliases(stmt, src, &mut aliases);
                    // Rust `pub use x as y`: other files call `y`; keep `x` alive from here.
                    let mut c = stmt.walk();
                    let is_reexport = stmt.kind() == "use_declaration"
                        && stmt
                            .children(&mut c)
                            .any(|ch| ch.kind() == "visibility_modifier");
                    if is_reexport && aliases.len() > n_before {
                        let line = stmt.start_position().row as u32 + 1;
                        let mut stack = vec![stmt];
                        let mut origs: Vec<String> = vec![];
                        while let Some(n) = stack.pop() {
                            if n.kind() == "use_as_clause" {
                                if let Some(o) = n.child_by_field_name("path") {
                                    let o = text(o, src);
                                    origs
                                        .push(o.rsplit([':', '.']).next().unwrap_or(o).to_string());
                                }
                            }
                            let mut cc = n.walk();
                            for ch in n.children(&mut cc) {
                                stack.push(ch);
                            }
                        }
                        for name in origs {
                            reexports.push((
                                stmt.start_byte(),
                                RefFact {
                                    name,
                                    kind: "references".into(),
                                    line,
                                    member: false,
                                    src: None,
                                },
                            ));
                        }
                    }
                }
            }
            if let (Some(stmt), None) = (stmt, &module) {
                name_only
                    .entry(stmt.id())
                    .or_default()
                    .extend(imp_names.iter().cloned());
            }
            if let (Some(stmt), Some(module)) = (stmt, module) {
                let kind = match stmt.kind() {
                    "mod_item" => "mod",
                    "extern_crate_declaration" => "extern_crate",
                    "call_expression" => {
                        if text(stmt, src).starts_with("require") {
                            "require"
                        } else {
                            "import"
                        }
                    }
                    _ => "import",
                };
                let kind = if kind == "import"
                    && family == Family::Python
                    && in_import_error_guard(stmt, src)
                {
                    "optional"
                } else {
                    kind
                };
                import_node_ids.insert(stmt.id());
                by_stmt.push((
                    stmt.id(),
                    ImportFact {
                        module,
                        names: imp_names,
                        line: stmt.start_position().row as u32 + 1,
                        kind: kind.into(),
                    },
                ));
                if family == Family::JsLike {
                    let mut stack = vec![stmt];
                    let last = by_stmt.last_mut().unwrap();
                    while let Some(n) = stack.pop() {
                        if matches!(n.kind(), "import_specifier" | "export_specifier") {
                            if let Some(nm) = n.child_by_field_name("name") {
                                last.1.names.push(text(nm, src).to_string());
                            }
                        }
                        let mut cc = n.walk();
                        for ch in n.children(&mut cc) {
                            stack.push(ch);
                        }
                    }
                }
            }
        }
    }
    // Merge python `from x import a, b` which yields one match per name: same stmt id + same module.
    let mut merged: Vec<ImportFact> = vec![];
    let mut seen: HashMap<(usize, String), usize> = HashMap::new();
    for (id, imp) in by_stmt {
        let mut imp = imp;
        if let Some(extra) = name_only.get(&id) {
            imp.names.extend(extra.iter().cloned());
        }
        let key = (id, imp.module.clone());
        if let Some(&i) = seen.get(&key) {
            for n in imp.names {
                if !merged[i].names.contains(&n) {
                    merged[i].names.push(n);
                }
            }
        } else {
            seen.insert(key, merged.len());
            imp.names.sort();
            imp.names.dedup();
            merged.push(imp);
        }
    }
    // For python: a name-only match (no module) is not produced; `from x import y` has both.
    facts.imports = merged;

    // ---- references & string mentions -------------------------------------
    let ref_kinds: HashSet<&str> = pack
        .manifest
        .ref_node_kinds
        .iter()
        .map(|s| s.as_str())
        .collect();
    let string_kinds: HashSet<&str> = pack
        .manifest
        .string_node_kinds
        .iter()
        .map(|s| s.as_str())
        .collect();
    let mut strings: BTreeSet<String> = BTreeSet::new();
    let mut refs: Vec<(usize, RefFact)> = std::mem::take(&mut reexports); // (byte, fact) with src filled afterwards

    let mut cursor = root.walk();
    let mut descended = true;
    loop {
        let node = cursor.node();
        if descended {
            let k = node.kind();
            let skip_subtree = import_node_ids.contains(&node.id());
            if !skip_subtree {
                if ref_kinds.contains(k)
                    && node.child_count() == 0
                    && !name_starts.contains(&node.start_byte())
                {
                    let t = text(node, src);
                    if !t.is_empty() {
                        let call = is_callee(node) || token_tree_call(node, src);
                        refs.push((
                            node.start_byte(),
                            RefFact {
                                name: t.to_string(),
                                kind: if call {
                                    "calls".into()
                                } else {
                                    "references".into()
                                },
                                line: node.start_position().row as u32 + 1,
                                member: is_member(node) || token_tree_member(node),
                                src: None,
                            },
                        ));
                    }
                } else if string_kinds.contains(k) {
                    let t = text(node, src);
                    if is_ident_like(t) {
                        strings.insert(t.to_string());
                    }
                    // Rust inline format args: "{NAME}" / "{name:?}" capture the identifier.
                    if pack.manifest.id == "rust" {
                        for name in inline_format_captures(t) {
                            refs.push((
                                node.start_byte(),
                                RefFact {
                                    name,
                                    kind: "references".into(),
                                    line: node.start_position().row as u32 + 1,
                                    member: false,
                                    src: None,
                                },
                            ));
                        }
                    }
                }
            }
            if !skip_subtree && cursor.goto_first_child() {
                continue;
            }
            descended = false;
        }
        if cursor.goto_next_sibling() {
            descended = true;
            continue;
        }
        if !cursor.goto_parent() {
            break;
        }
    }
    // Enclosing symbol sweep (refs are in document order).
    {
        let mut next = 0usize;
        let mut stack: Vec<usize> = vec![];
        for (b, r) in refs.iter_mut() {
            while next < syms.len() && syms[next].start_byte <= *b {
                stack.push(next);
                next += 1;
            }
            while let Some(&t) = stack.last() {
                if syms[t].end_byte <= *b {
                    stack.pop();
                } else {
                    break;
                }
            }
            r.src = stack.last().copied();
        }
    }
    for (_, r) in refs.iter_mut() {
        if let Some(orig) = aliases.get(&r.name) {
            // a local definition with the alias's name wins
            if !syms.iter().any(|s| s.name == r.name) {
                r.name = orig.clone();
            }
        }
    }
    facts.refs = refs.into_iter().map(|(_, r)| r).collect();
    facts.symbols = syms;
    facts.strings = strings;
    Ok(facts)
}

/// True when `stmt` sits in the body of a Python `try:` whose handlers catch ImportError /
/// ModuleNotFoundError (or are bare): the import is an optional-dependency / compat probe.
fn in_import_error_guard(stmt: tree_sitter::Node, src: &[u8]) -> bool {
    let mut child = stmt;
    while let Some(p) = child.parent() {
        match p.kind() {
            "function_definition" | "class_definition" => return false,
            "try_statement" => {
                // only the `try:` body counts, not handlers / else / finally
                let in_body = p
                    .child_by_field_name("body")
                    .map(|b| b.id() == child.id())
                    .unwrap_or(false);
                if in_body {
                    let mut c = p.walk();
                    let catches = p.children(&mut c).any(|h| {
                        if h.kind() != "except_clause" && h.kind() != "except_group_clause" {
                            return false;
                        }
                        let t = text(h, src);
                        let head = t.lines().next().unwrap_or("");
                        head.contains("ImportError")
                            || head.contains("ModuleNotFoundError")
                            || head.trim_start_matches("except").trim().starts_with(':')
                    });
                    if catches {
                        return true;
                    }
                }
            }
            _ => {}
        }
        child = p;
    }
    false
}

/// Collect `original as alias` pairs from an import statement (Rust `use_as_clause`, Python
/// `aliased_import`, JS/TS `import_specifier`). The original is the last path segment.
fn collect_import_aliases(stmt: tree_sitter::Node, src: &[u8], out: &mut HashMap<String, String>) {
    let mut stack = vec![stmt];
    while let Some(n) = stack.pop() {
        let (orig_field, alias_field) = match n.kind() {
            "use_as_clause" => ("path", "alias"),
            "aliased_import" | "import_specifier" => ("name", "alias"),
            _ => ("", ""),
        };
        if !orig_field.is_empty() {
            if let (Some(o), Some(a)) = (
                n.child_by_field_name(orig_field),
                n.child_by_field_name(alias_field),
            ) {
                let o = text(o, src);
                let orig = o.rsplit([':', '.']).next().unwrap_or(o);
                let alias = text(a, src);
                if !orig.is_empty() && !alias.is_empty() && orig != alias {
                    out.insert(alias.to_string(), orig.to_string());
                }
            }
        }
        let mut cc = n.walk();
        for ch in n.children(&mut cc) {
            stack.push(ch);
        }
    }
}

/// Name of the first annotation on a Java declaration that is not a compiler/lint marker.
/// Such methods (`@Test`, `@BeforeExperiment`, `@Bean`, `@Scheduled`, ...) are called by a
/// framework, never by name from the indexed code.
fn java_framework_annotation(def: tree_sitter::Node, src: &[u8]) -> Option<String> {
    const PLAIN: &[&str] = &[
        "Override",
        "Deprecated",
        "SuppressWarnings",
        "SafeVarargs",
        "FunctionalInterface",
        "Nullable",
        "NonNull",
        "CheckForNull",
        "CanIgnoreReturnValue",
        "VisibleForTesting",
    ];
    let mut c = def.walk();
    let mods = def.children(&mut c).find(|n| n.kind() == "modifiers")?;
    let mut c2 = mods.walk();
    for a in mods.children(&mut c2) {
        if matches!(a.kind(), "marker_annotation" | "annotation") {
            let name = a.child_by_field_name("name").map(|n| text(n, src))?;
            let short = name.rsplit('.').next().unwrap_or(name);
            if !PLAIN.contains(&short) {
                return Some(short.to_string());
            }
        }
    }
    None
}

/// Identifiers captured by Rust inline format args inside a string literal, e.g. `{END}`, `{x:?}`.
/// `{{` is an escaped brace and is skipped. Over-approximating is safe (it only suppresses
/// dead-code findings); a plain-text `{word}` in a non-format string is the accepted false negative.
fn inline_format_captures(lit: &str) -> Vec<String> {
    let b = lit.as_bytes();
    let mut out = vec![];
    let mut i = 0;
    while i < b.len() {
        if b[i] == b'{' {
            if i + 1 < b.len() && b[i + 1] == b'{' {
                i += 2;
                continue;
            }
            let start = i + 1;
            let mut j = start;
            while j < b.len() && (b[j].is_ascii_alphanumeric() || b[j] == b'_') {
                j += 1;
            }
            if j > start
                && !b[start].is_ascii_digit()
                && j < b.len()
                && (b[j] == b'}' || b[j] == b':')
            {
                out.push(lit[start..j].to_string());
            }
            i = j.max(i + 1);
        } else {
            i += 1;
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use plumbgraph_langs::PackSet;

    fn ex(pack: &str, path: &str, src: &str) -> FileFacts {
        let set = PackSet::builtin().unwrap();
        extract(set.by_id(pack).unwrap(), path, src).unwrap()
    }
    fn sym<'a>(f: &'a FileFacts, name: &str) -> &'a SymbolFact {
        f.symbols
            .iter()
            .find(|s| s.name == name)
            .unwrap_or_else(|| {
                panic!(
                    "no symbol {name}: {:?}",
                    f.symbols.iter().map(|s| &s.name).collect::<Vec<_>>()
                )
            })
    }

    #[test]
    fn python_symbols_imports_refs() {
        let f = ex(
            "python",
            "pkg/mod.py",
            "import os, json as j\nfrom .util import helper as h, other\nfrom pkg.sub import thing\n\nclass Foo:\n    def __init__(self):\n        self.x = helper()\n    def bar(self):\n        return self.baz()\n    def _priv(self): pass\n\n@app.route('/x')\ndef view():\n    return Foo().bar()\n\ndef _unused(): pass\n",
        );
        assert_eq!(sym(&f, "Foo").kind, "class");
        assert_eq!(sym(&f, "bar").kind, "method");
        assert_eq!(sym(&f, "bar").qname, "Foo.bar");
        assert!(sym(&f, "bar").exported);
        assert!(!sym(&f, "_priv").exported);
        assert_eq!(sym(&f, "__init__").entry.as_deref(), Some("dunder method"));
        assert!(sym(&f, "view").decorated);
        assert!(!sym(&f, "_unused").exported);
        let mods: Vec<_> = f.imports.iter().map(|i| i.module.as_str()).collect();
        assert!(
            mods.contains(&"os")
                && mods.contains(&"json")
                && mods.contains(&".util")
                && mods.contains(&"pkg.sub"),
            "{mods:?}"
        );
        let util = f.imports.iter().find(|i| i.module == ".util").unwrap();
        assert_eq!(util.names, vec!["helper".to_string(), "other".to_string()]);
        // `helper()` call inside __init__ is a call ref enclosed by __init__
        let r = f.refs.iter().find(|r| r.name == "helper").unwrap();
        assert_eq!(r.kind, "calls");
        assert_eq!(f.symbols[r.src.unwrap()].name, "__init__");
        // self.baz() is a member call
        let b = f.refs.iter().find(|r| r.name == "baz").unwrap();
        assert!(b.member && b.kind == "calls");
        // imported names are not counted as references
        assert!(!f.refs.iter().any(|r| r.name == "thing"));
    }

    #[test]
    fn js_symbols_exports_imports() {
        let f = ex(
            "javascript",
            "src/a.js",
            "import fs from 'node:fs';\nimport { used, other as o } from './b.js';\nconst lodash = require('lodash');\nexport function pub() { return used(); }\nfunction priv() {}\nconst arrow = () => 1;\nexport const val = 3;\nclass K { constructor() {} go() { priv(); } }\nfunction outer() { const inner = () => 2; return inner(); }\n",
        );
        assert!(sym(&f, "pub").exported);
        assert!(!sym(&f, "priv").exported);
        assert_eq!(sym(&f, "arrow").kind, "function");
        assert_eq!(sym(&f, "val").kind, "variable");
        assert_eq!(sym(&f, "go").kind, "method");
        assert_eq!(sym(&f, "constructor").entry_cond.as_deref(), Some("parent"));
        assert!(
            !f.symbols.iter().any(|s| s.name == "inner"),
            "nested const must not be a symbol"
        );
        let mods: Vec<_> = f
            .imports
            .iter()
            .map(|i| (i.module.as_str(), i.kind.as_str()))
            .collect();
        assert!(mods.contains(&("node:fs", "import")), "{mods:?}");
        assert!(mods.contains(&("./b.js", "import")));
        assert!(mods.contains(&("lodash", "require")));
        let b = f.imports.iter().find(|i| i.module == "./b.js").unwrap();
        assert!(b.names.contains(&"used".to_string()) && b.names.contains(&"other".to_string()));
        let c = f.refs.iter().find(|r| r.name == "priv").unwrap();
        assert_eq!(c.kind, "calls");
    }

    #[test]
    fn typescript_interfaces_types() {
        let f = ex("typescript", "src/t.ts", "export interface Shape { area(): number }\ntype Id = string;\nenum Color { Red }\nexport class Sq implements Shape { area() { return 1 } }\n");
        assert_eq!(sym(&f, "Shape").kind, "interface");
        assert_eq!(sym(&f, "Id").kind, "type");
        assert_eq!(sym(&f, "Color").kind, "enum");
        assert!(sym(&f, "Sq").exported);
        assert!(f.refs.iter().any(|r| r.name == "Shape"));
    }

    #[test]
    fn tsx_parses() {
        let f = ex("tsx", "src/c.tsx", "export function App() { return <Foo a={1}/>; }\nfunction Foo(p: {a: number}) { return <div/>; }\n");
        assert!(!f.has_syntax_errors);
        assert!(f.refs.iter().any(|r| r.name == "Foo"));
    }

    #[test]
    fn rust_symbols_attrs_methods() {
        let f = ex(
            "rust",
            "src/lib.rs",
            "use std::fmt;\nuse crate::other::Thing;\nmod inner;\npub struct S;\nimpl S { pub fn new() -> S { S } fn hidden(&self) { helper(); } }\nimpl fmt::Display for S { fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result { Ok(()) } }\nfn helper() {}\n#[no_mangle]\npub extern \"C\" fn ffi() {}\n#[cfg(test)]\nmod tests { use super::*; #[test] fn t() { helper(); } }\nfn main() {}\n",
        );
        assert!(sym(&f, "S").exported);
        assert_eq!(sym(&f, "new").kind, "method");
        assert_eq!(sym(&f, "new").qname, "S::new");
        assert!(sym(&f, "new").exported);
        assert!(!sym(&f, "hidden").exported);
        assert_eq!(sym(&f, "fmt").entry.as_deref(), Some("trait impl method"));
        assert_eq!(sym(&f, "fmt").entry_cond.as_deref(), Some("type:S"));
        assert!(sym(&f, "ffi").entry.is_some());
        assert!(sym(&f, "t").is_test);
        assert!(sym(&f, "tests").is_test);
        assert!(
            sym(&f, "main").entry.is_none(),
            "main in lib.rs is not an entry"
        );
        let mods: Vec<_> = f
            .imports
            .iter()
            .map(|i| (i.module.as_str(), i.kind.as_str()))
            .collect();
        assert!(mods.contains(&("std::fmt", "import")), "{mods:?}");
        assert!(mods.contains(&("inner", "mod")));
        assert!(!f.has_syntax_errors);
    }

    #[test]
    fn rust_main_in_main_rs_is_entry() {
        let f = ex("rust", "src/main.rs", "fn main() {}");
        assert!(sym(&f, "main").entry.is_some());
    }

    #[test]
    fn keep_annotation_and_generated() {
        let f = ex(
            "python",
            "a.py",
            "# plumb:keep(public hook)\ndef hook(): pass\n",
        );
        assert_eq!(sym(&f, "hook").keep.as_deref(), Some("public hook"));
        let g = ex("python", "a.py", "# @generated\ndef x(): pass\n");
        assert!(g.is_generated);
    }

    #[test]
    fn rust_inline_format_args_are_references() {
        let f = ex(
            "rust",
            "a.rs",
            "const END: &str = \"x\";\nfn f() -> String { format!(\"a{END}b {{NOT}} {n:?}\") }\n",
        );
        assert!(f.refs.iter().any(|r| r.name == "END"), "{:?}", f.refs);
        assert!(f.refs.iter().any(|r| r.name == "n"));
        assert!(!f.refs.iter().any(|r| r.name == "NOT"));
    }

    #[test]
    fn java_main_and_serialization_hooks_are_entries() {
        let f = ex(
            "java",
            "A.java",
            "class A implements java.io.Serializable {\n public static void main(String[] a) { helper(); }\n static void helper() {}\n private Object writeReplace() { return this; }\n private void readObject(java.io.ObjectInputStream i) {}\n void other() {}\n}\n",
        );
        assert!(sym(&f, "main").entry.is_some());
        assert!(sym(&f, "writeReplace").entry.is_some());
        assert!(sym(&f, "readObject").entry.is_some());
        assert!(sym(&f, "other").entry.is_none());
        let g = ex(
            "java",
            "B.java",
            "class B {\n @BeforeExperiment void setUp() {}\n @Override public String toString() { return \"\"; }\n @SuppressWarnings(\"x\") void plain() {}\n}\n",
        );
        assert!(sym(&g, "setUp").entry.is_some());
        assert!(sym(&g, "plain").entry.is_none());
        let c = ex(
            "csharp",
            "A.cs",
            "class P { static void Main(string[] a) { } }\n",
        );
        assert!(sym(&c, "Main").entry.is_some());
    }

    #[test]
    fn string_mentions_and_dynamic_markers() {
        let f = ex(
            "python",
            "a.py",
            "def foo(): pass\nx = getattr(m, \"foo\")\n",
        );
        assert!(f.strings.contains("foo"));
        assert!(f.dynamic_markers.contains(&"getattr".to_string()));
    }

    #[test]
    fn test_path_globs() {
        let set = PackSet::builtin().unwrap();
        assert!(is_test_path(
            set.by_id("python").unwrap(),
            "pkg/tests/test_x.py"
        ));
        assert!(is_test_path(set.by_id("python").unwrap(), "test_x.py"));
        assert!(is_test_path(
            set.by_id("javascript").unwrap(),
            "src/a.test.js"
        ));
        assert!(!is_test_path(set.by_id("javascript").unwrap(), "src/a.js"));
    }

    #[test]
    fn aliased_imports_count_as_references_to_the_original_name() {
        // `use x as y`, `from m import x as y`, `import { x as y }`: a use of the alias is a use of `x`.
        let f = ex(
            "rust",
            "src/main.rs",
            "use util::{helper as h, other::deep as d};\nfn main() { h(); d(); }\n",
        );
        let names: Vec<_> = f.refs.iter().map(|r| r.name.as_str()).collect();
        assert!(
            names.contains(&"helper") && names.contains(&"deep"),
            "rust: {names:?}"
        );
        let f = ex(
            "python",
            "a.py",
            "from b import helper as h\ndef main():\n    h()\n",
        );
        let names: Vec<_> = f.refs.iter().map(|r| r.name.as_str()).collect();
        assert!(names.contains(&"helper"), "python: {names:?}");
        let f = ex(
            "javascript",
            "a.js",
            "import { helper as h } from './b.js';\nh();\n",
        );
        let names: Vec<_> = f.refs.iter().map(|r| r.name.as_str()).collect();
        assert!(names.contains(&"helper"), "js: {names:?}");
        // a local symbol that shadows the alias name keeps its own refs
        let f = ex(
            "python",
            "a.py",
            "from b import helper as h\ndef h2(): pass\nh2()\n",
        );
        assert!(f.refs.iter().any(|r| r.name == "h2"));
    }

    #[test]
    fn rust_pub_use_alias_reexport_keeps_the_original_alive() {
        // `pub(crate) use m::f as g;` is how ripgrep exposes `generate_long`; callers elsewhere
        // use `g`, which a per-file alias table cannot see. The re-export itself references `f`.
        let f = ex(
            "rust",
            "mod.rs",
            "pub(crate) use crate::doc::{generate_long as generate_help_long};\nuse crate::x::priv_fn as p;\n",
        );
        assert!(
            f.refs.iter().any(|r| r.name == "generate_long"),
            "{:?}",
            f.refs
        );
        // a private `use ... as` is not a re-export
        assert!(!f.refs.iter().any(|r| r.name == "priv_fn"));
    }

    #[test]
    fn go_methods_are_qualified_by_receiver_type() {
        let f = ex("go", "a.go", "package a\ntype Context struct{}\ntype Box[T any] struct{}\nfunc (c *Context) JSON() {}\nfunc (b Box[T]) Get() {}\nfunc Free() {}\n");
        assert_eq!(sym(&f, "JSON").qname, "Context.JSON");
        assert_eq!(sym(&f, "Get").qname, "Box.Get");
        assert_eq!(sym(&f, "Free").qname, "Free");
    }
}
